/* Generated by ncc (NihaoC -> C transpiler) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
/* NihaoC visibility enum */
enum nihao_vis { NH_UNDEF=0, NH_CONST, NH_FLOW, NH_STATIC, NH_VAR };

int32_t add(int32_t a, int32_t b) {
    return a + b;
}
int main() {
    int32_t x = add(3, 4);
    if (x > 5){
        puts("big");
    }
    else{
        puts("small");
    }
    puts("hello nihao");
    return 0;
}
