#include "ir_backend.h"
#include "ir.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============================================================
 * 目标后端框架：NBuf + 后端注册表 + 统一发射骨架
 *
 * 骨架只负责平台无关部分：
 *   - 字符串池发射
 *   - 函数循环 + 帧大小计算（用 tb 布局参数）
 *   - 调 tb->fn_prologue → tb->emit_ins（每条指令）→ tb->fn_epilogue
 * 其余（栈帧布局、调用约定、指令选择、浮点）全部由各后端实现。
 * ============================================================ */

void nb_init(NBuf *b)
{
    b->buf = NULL;
    b->len = b->cap = 0;
}

void nb_put(NBuf *b, const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    va_list ap2;
    va_copy(ap2, ap);
    int need = vsnprintf(NULL, 0, fmt, ap);
    va_end(ap);
    if (need < 0) { va_end(ap2); return; }
    size_t nl = b->len + (size_t)need + 1;
    if (nl > b->cap) {
        size_t nc = b->cap ? b->cap : 256;
        while (nc < nl) nc *= 2;
        char *nb2 = nihao_realloc(g_cs, b->buf, nc);
        if (!nb2) { va_end(ap2); return; }
        b->buf = nb2;
        b->cap = nc;
    }
    vsnprintf(b->buf + b->len, b->cap - b->len, fmt, ap2);
    va_end(ap2);
    b->len += (size_t)need;
}

/* 后端注册表（阶段 1：x86-64；阶段 3：+riscv64） */
static const TargetBackend *g_backends[] = {
    &x86_64_backend,
    &riscv64_backend,
};

const TargetBackend *backend_find(const char *name)
{
    for (size_t i = 0; i < sizeof(g_backends) / sizeof(g_backends[0]); i++) {
        if (strcmp(g_backends[i]->name, name) == 0)
            return g_backends[i];
    }
    return NULL;
}

int backend_count(void)
{
    return (int)(sizeof(g_backends) / sizeof(g_backends[0]));
}

const char *backend_name(int idx)
{
    if (idx < 0 || idx >= backend_count()) return NULL;
    return g_backends[idx]->name;
}

/* 统一发射入口 */
int irgen_backend_emit(IrProg *p, const char *outfile, const char *backend)
{
    const TargetBackend *tb = backend_find(backend);
    if (!tb) {
        fprintf(stderr, "ir-backend: unknown backend '%s'\n", backend);
        return -1;
    }

    NBuf b;
    nb_init(&b);
    nb_put(&b, "# Generated by ncc IR -> %s backend\n", tb->name);
    nb_put(&b, ".text\n");

    /* 字符串池 */
    if (p->str_count > 0) {
        nb_put(&b, ".section .rodata\n");
        for (int i = 0; i < p->str_count; i++) {
            nb_put(&b, "%s:\n", p->str_syms[i]);
            nb_put(&b, "  .string \"%s\"\n", p->str_data[i]);
        }
        nb_put(&b, ".text\n");
    }

    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        /* 帧大小：槽区（vreg_count+1 个槽 × stride）+ 额外开销，向上取整对齐 */
        int frame = tb->slot_stride * (f->vreg_count + 1) + tb->frame_extra;
        if (frame % tb->callee_align != 0)
            frame += tb->callee_align - (frame % tb->callee_align);

        if (f->is_main) {
            nb_put(&b, ".globl main\n");
        }
        nb_put(&b, "%s:\n", f->name);

        if (tb->fn_prologue) tb->fn_prologue(&b, tb, f, frame);

        /* 指令循环 */
        for (int i = 0; i < f->ins_count; i++) {
            IrIns *in = &f->ins[i];
            if (in->op == IR_ALLOCA || in->op == IR_PARAM) continue;
            if (tb->emit_ins) tb->emit_ins(&b, in, tb, p, f, i);
        }

        /* 函数尾：无显式 return 时补隐式返回 */
        int need_ret = 1;
        for (int i = f->ins_count - 1; i >= 0; i--) {
            if (f->ins[i].op == IR_LABEL || f->ins[i].op == IR_END) continue;
            if (f->ins[i].op == IR_RET) need_ret = 0;
            break;
        }
        if (tb->fn_epilogue) tb->fn_epilogue(&b, tb, f, need_ret);
        nb_put(&b, "\n");
    }

    FILE *fp = fopen(outfile, "wb");
    if (!fp) {
        fprintf(stderr, "ir-backend: cannot write '%s'\n", outfile);
        return -1;
    }
    fputs(b.buf ? b.buf : "", fp);
    fclose(fp);
    if (b.buf) free(b.buf);
    return 0;
}
