/* ============================================================
 * ir_to_c.c - IR -> C 后端（方案 B）
 * 每条 IR 指令翻译为一行 C，字符串池输出为静态数组
 * ============================================================ */
#include "ir.h"

typedef struct {
    char *buf;
    int len, cap;
} CBuf;

static void cb_init(CBuf *b)
{
    b->cap = 4096;
    b->buf = nihao_malloc(g_cs, b->cap);
    b->buf[0] = '\0';
    b->len = 0;
}

static void cb_put(CBuf *b, const char *fmt, ...)
{
    char tmp[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(tmp, sizeof(tmp), fmt, ap);
    va_end(ap);
    int n = (int)strlen(tmp);
    if (b->len + n + 1 > b->cap) {
        b->cap = (b->len + n + 1) * 2;
        b->buf = nihao_realloc(g_cs, b->buf, b->cap);
    }
    memcpy(b->buf + b->len, tmp, n);
    b->len += n;
    b->buf[b->len] = '\0';
}

static const char *cmp_op(IrOp op)
{
    switch (op) {
        case IR_CMP_EQ: return "==";
        case IR_CMP_NE: return "!=";
        case IR_CMP_LT: return "<";
        case IR_CMP_LE: return "<=";
        case IR_CMP_GT: return ">";
        case IR_CMP_GE: return ">=";
        default: return "?";
    }
}

static const char *bin_op(IrOp op)
{
    switch (op) {
        case IR_ADD: return "+";
        case IR_SUB: return "-";
        case IR_MUL: return "*";
        case IR_DIV: return "/";
        case IR_MOD: return "%";
        case IR_SHL: return "<<";
        case IR_SHR: return ">>";
        case IR_AND: return "&";
        case IR_OR:  return "|";
        default: return "?";
    }
}

/* PB-18：参数 vreg 是否为字符串池地址（LD_ADDR __str_N）——puts 等外部函数
 * 需要 char*，IR 层统一 int64，生成 C 时包 (char*) 消除 pointer-from-integer 警告 */
static int is_str_addr(const IrFn *f, int vr)
{
    for (int k = 0; k < f->ins_count; k++) {
        if (f->ins[k].op == IR_LD_ADDR && f->ins[k].dst == vr &&
            f->ins[k].sym && strncmp(f->ins[k].sym, "__str_", 6) == 0) {
            return 1;
        }
    }
    return 0;
}

int irgen_c_emit(IrProg *p, const char *outfile)
{
    CBuf b;
    cb_init(&b);
    cb_put(&b, "/* Generated by ncc IR -> C backend */\n");
    cb_put(&b, "#include <stdio.h>\n#include <stdlib.h>\n#include <stdint.h>\n\n");

    /* 字符串池 */
    for (int i = 0; i < p->str_count; i++) {
        cb_put(&b, "static const char %s[] = \"%s\";\n",
               p->str_syms[i], p->str_data[i]);
    }
    if (p->str_count) cb_put(&b, "\n");

    /* 用户函数前置原型：消除"调用先于定义"导致的隐式声明
     * （Windows tcc 对隐式声明的未知符号生成 __imp_ 外部引用而链接失败） */
    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        cb_put(&b, "%s %s(", f->ret_is_double ? "double" : "int64_t", f->name);
        for (int i = 0; i < f->param_count; i++) {
            cb_put(&b, "%s%s arg%d", i ? ", " : "",
                   f->param_types[i] == 1 ? "double" : "int64_t", i);
        }
        cb_put(&b, ");\n");
    }
    if (p->fn_count) cb_put(&b, "\n");

    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        cb_put(&b, "%s %s(", f->ret_is_double ? "double" : "int64_t", f->name);
        for (int i = 0; i < f->param_count; i++) {
            /* 参数名: 子集固定 argN（由 parser 顺序声明） */
            cb_put(&b, "%s%s arg%d", i ? ", " : "",
                   f->param_types[i] == 1 ? "double" : "int64_t", i);
        }
        cb_put(&b, ") {\n");

        /* PB 阶段3 C 项：构建 vreg 标识符表——有名用源码名，无名用 tN（与声明一致）。
         * 用于局部变量声明与全部指令操作数引用，使生成 C 可读。 */
        char **vrid = NULL;
        if (f->vreg_count > 0) {
            vrid = nihao_malloc(g_cs, f->vreg_count * sizeof(char *));
            for (int i = 0; i < f->vreg_count; i++) {
                if (f->vreg_name && i < f->vreg_count && f->vreg_name[i]) {
                    vrid[i] = nihao_strdup(g_cs, f->vreg_name[i]);
                } else {
                    char tmp[32];
                    snprintf(tmp, sizeof(tmp), "t%d", i);
                    vrid[i] = nihao_strdup(g_cs, tmp);
                }
            }
        }

        /* 局部变量声明：遍历全部 vreg——数组基（ALLOCA imm>8）声明为
         * C 数组 vrid[i][imm/8]；其余（标量槽/临时）声明单变量。
         * 数组元素 vreg 无 ALLOCA 也声明（未被引用，无害）。 */
        if (f->vreg_count > 0) {
            for (int i = 0; i < f->vreg_count; i++) {
                long long asz = -1;
                for (int ai = 0; ai < f->ins_count; ai++) {
                    if (f->ins[ai].op == IR_ALLOCA && f->ins[ai].dst == i) {
                        asz = (long long)f->ins[ai].imm;
                        break;
                    }
                }
                if (asz > 8) {
                    cb_put(&b, "    int64_t %s[%lld];\n", vrid[i], asz / 8);
                } else {
                    cb_put(&b, "    %s %s;\n",
                           (f->vreg_type && f->vreg_type[i] == 1) ? "double" : "int64_t",
                           vrid[i]);
                }
            }
        }
        /* 参数绑定到 vreg 0..nparam-1（parser 先 declare 的参数在 vreg 0..） */
        for (int i = 0; i < f->param_count; i++) {
            cb_put(&b, "    %s = arg%d;\n", vrid[i], i);
        }
        /* 指令（操作数统一用 vrid：有名变量读源码名，无名临时读 tN，与声明一致） */
        for (int i = 0; i < f->ins_count; i++) {
            IrIns *in = &f->ins[i];
            switch (in->op) {
                case IR_CONST:
                    if (f->vreg_type && in->dst >= 0 && in->dst < f->vreg_count &&
                        f->vreg_type[in->dst] == 1) {
                        /* 浮点常量：imm 是 double 位模式 */
                        union { int64_t i; double d; } u;
                        u.i = in->imm;
                        cb_put(&b, "    %s = %.17g;\n", vrid[in->dst], u.d);
                    } else {
                        cb_put(&b, "    %s = %lld;\n", vrid[in->dst], (long long)in->imm);
                    }
                    break;
                case IR_MOV:
                    cb_put(&b, "    %s = %s;\n", vrid[in->dst], vrid[in->a]);
                    break;
                case IR_ADD: case IR_SUB: case IR_MUL:
                case IR_DIV: case IR_MOD:
                case IR_SHL: case IR_SHR: case IR_AND: case IR_OR:
                    cb_put(&b, "    %s = %s %s %s;\n",
                           vrid[in->dst], vrid[in->a], bin_op(in->op), vrid[in->b]);
                    break;
                case IR_FADD: case IR_FSUB: case IR_FMUL: case IR_FDIV:
                    cb_put(&b, "    %s = %s %s %s;\n",
                           vrid[in->dst], vrid[in->a],
                           in->op == IR_FADD ? "+" :
                           in->op == IR_FSUB ? "-" :
                           in->op == IR_FMUL ? "*" : "/",
                           vrid[in->b]);
                    break;
                case IR_ITOD:
                    cb_put(&b, "    %s = (double)%s;\n", vrid[in->dst], vrid[in->a]);
                    break;
                case IR_DTOI:
                    cb_put(&b, "    %s = (int64_t)%s;\n", vrid[in->dst], vrid[in->a]);
                    break;
                case IR_FTRUNC:
                    cb_put(&b, "    %s = (float)%s;\n", vrid[in->dst], vrid[in->a]);
                    break;
                case IR_TRUNC:
                    /* 窄整数截断 + 符号/零扩展（imm: 0=i8 1=i16 2=i32 3=u8 4=u16 5=u32） */
                    cb_put(&b, "    %s = (%s)%s;\n", vrid[in->dst],
                           in->imm == 0 ? "int8_t" : in->imm == 1 ? "int16_t" :
                           in->imm == 2 ? "int32_t" : in->imm == 3 ? "uint8_t" :
                           in->imm == 4 ? "uint16_t" : "uint32_t", vrid[in->a]);
                    break;
                case IR_FCMP:
                    cb_put(&b, "    %s = (%s %s %s);\n",
                           vrid[in->dst], vrid[in->a],
                           in->imm == 0 ? "==" : in->imm == 1 ? "!=" :
                           in->imm == 2 ? "<"  : in->imm == 3 ? "<=" :
                           in->imm == 4 ? ">"  : ">=",
                           vrid[in->b]);
                    break;
                case IR_NEG:
                    cb_put(&b, "    %s = -%s;\n", vrid[in->dst], vrid[in->a]);
                    break;
                case IR_NOT:
                    cb_put(&b, "    %s = ~%s;\n", vrid[in->dst], vrid[in->a]);
                    break;
                case IR_CMP_EQ: case IR_CMP_NE: case IR_CMP_LT:
                case IR_CMP_LE: case IR_CMP_GT: case IR_CMP_GE:
                    cb_put(&b, "    %s = (%s %s %s);\n",
                           vrid[in->dst], vrid[in->a], cmp_op(in->op), vrid[in->b]);
                    break;
                case IR_JMP:
                    cb_put(&b, "    goto L%d;\n", in->label);
                    break;
                case IR_JZ:
                    cb_put(&b, "    if (!%s) goto L%d;\n", vrid[in->a], in->label);
                    break;
                case IR_JNZ:
                    cb_put(&b, "    if (%s) goto L%d;\n", vrid[in->a], in->label);
                    break;
                case IR_LABEL:
                    cb_put(&b, "L%d:;\n", in->label);
                    break;
                case IR_LD_ADDR:
                    cb_put(&b, "    %s = (int64_t)(intptr_t)%s;\n", vrid[in->dst], in->sym);
                    break;
                case IR_ALLOCA:
                    /* C 中局部变量已声明；ALLOCA 槽即 vrid */
                    break;
                case IR_ADDR:
                    /* 平铺槽（imm=8）：&vrid{a+imm} 直接引用槽 vreg；
                     * 基本数组基（imm>8）：&vrid{a}[imm]（C 数组元素，字节连续） */
                    {
                        long long asz = 8;
                        for (int ai = 0; ai < f->ins_count; ai++) {
                            if (f->ins[ai].op == IR_ALLOCA &&
                                f->ins[ai].dst == in->a) {
                                asz = (long long)f->ins[ai].imm;
                                break;
                            }
                        }
                        if (asz > 8) {
                            cb_put(&b, "    %s = (int64_t)(intptr_t)&%s[%lld];\n",
                                   vrid[in->dst], vrid[in->a], (long long)in->imm);
                        } else {
                            cb_put(&b, "    %s = (int64_t)(intptr_t)&%s;\n",
                                   vrid[in->dst], vrid[in->a + (int)in->imm]);
                        }
                    }
                    break;
                case IR_ELEM_ADDR:
                    /* 元素地址 = 基址 + idx*width（imm=宽度，0 兼容=8） */
                    cb_put(&b, "    %s = %s + %s * %d;\n",
                           vrid[in->dst], vrid[in->a], vrid[in->b],
                           in->imm == 1 ? 1 : in->imm == 2 ? 2 :
                           in->imm == 4 ? 4 : 8);
                    break;
                case IR_LOAD:
                    /* 类型感知存取（PB-1 数组元素宽度/浮点数组）：dst 标记 double → double 指针 */
                    cb_put(&b, "    %s = *(%s*)(intptr_t)%s;\n",
                           vrid[in->dst],
                           (f->vreg_type && in->dst < f->vreg_count &&
                            f->vreg_type[in->dst] == 1) ? "double" : "int64_t",
                           vrid[in->a]);
                    break;
                case IR_STORE:
                    /* 源 vreg 为 double → double 指针（否则 int64 截断 double 位模式） */
                    cb_put(&b, "    *(%s*)(intptr_t)%s = %s;\n",
                           (f->vreg_type && in->b < f->vreg_count &&
                            f->vreg_type[in->b] == 1) ? "double" : "int64_t",
                           vrid[in->a], vrid[in->b]);
                    break;
                case IR_LOAD8:
                    cb_put(&b, "    %s = *(uint8_t*)(intptr_t)%s;\n",
                           vrid[in->dst], vrid[in->a]);
                    break;
                case IR_STORE8:
                    cb_put(&b, "    *(uint8_t*)(intptr_t)%s = %s;\n",
                           vrid[in->a], vrid[in->b]);
                    break;
                case IR_RET:
                    if (in->a >= 0)
                        cb_put(&b, "    return %s;\n", vrid[in->a]);
                    else
                        cb_put(&b, "    return 0;\n");
                    break;
                case IR_PARAM:
                    /* 收集：由紧随其后的 CALL 处理 */
                    break;
                case IR_CALL: {
                    /* 取本 CALL 前最近的 nargs 个 PARAM */
                    int nargs = (int)in->imm;
                    int temp[64];
                    int tc = 0;
                    for (int k = 0; k < i && tc < 64; k++) {
                        if (f->ins[k].op == IR_PARAM) temp[tc++] = f->ins[k].a;
                    }
                    int start = tc > nargs ? tc - nargs : 0;
                    /* malloc 返回 void* → 显式 (int64_t)(intptr_t) 消除警告 */
                    cb_put(&b, "    %s = %s%s(", vrid[in->dst],
                           (in->sym && strcmp(in->sym, "malloc") == 0) ?
                               "(int64_t)(intptr_t)" : "",
                           in->sym);
                    for (int k = start; k < tc; k++) {
                        cb_put(&b, "%s%s", k > start ? ", " : "",
                               is_str_addr(f, temp[k]) ? "(char*)" : "");
                        cb_put(&b, "%s", vrid[temp[k]]);
                    }
                    cb_put(&b, ");\n");
                    break;
                }
                case IR_CALLI: {
                    /* 间接调用：dst = call *(a)，旧式无原型函数指针 */
                    int nargs = (int)in->imm;
                    int temp[64];
                    int tc = 0;
                    for (int k = 0; k < i && tc < 64; k++) {
                        if (f->ins[k].op == IR_PARAM) temp[tc++] = f->ins[k].a;
                    }
                    int start = tc > nargs ? tc - nargs : 0;
                    cb_put(&b, "    %s = ((int64_t (*)())%s)(", vrid[in->dst], vrid[in->a]);
                    for (int k = start; k < tc; k++) {
                        cb_put(&b, "%s%s", k > start ? ", " : "",
                               is_str_addr(f, temp[k]) ? "(char*)" : "");
                        cb_put(&b, "%s", vrid[temp[k]]);
                    }
                    cb_put(&b, ");\n");
                    break;
                }
                default:
                    break;
            }
        }
        cb_put(&b, "    return 0;\n}\n\n");
    }

    FILE *fp = fopen(outfile, "wb");
    if (!fp) {
        fprintf(stderr, "ir-c: cannot write '%s'\n", outfile);
        return -1;
    }
    fputs(b.buf, fp);
    fclose(fp);
    if (g_cs && g_cs->verbose) {
        printf("IR->C written to %s (%d bytes)\n", outfile, b.len);
    }
    return 0;
}
