/* ============================================================
 * ir_to_c.c - IR -> C 后端（方案 B）
 * 每条 IR 指令翻译为一行 C，字符串池输出为静态数组
 * ============================================================ */
#include "ir.h"

typedef struct {
    char *buf;
    int len, cap;
} CBuf;

static void cb_init(CBuf *b)
{
    b->cap = 4096;
    b->buf = nihao_malloc(g_cs, b->cap);
    b->buf[0] = '\0';
    b->len = 0;
}

static void cb_put(CBuf *b, const char *fmt, ...)
{
    char tmp[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(tmp, sizeof(tmp), fmt, ap);
    va_end(ap);
    int n = (int)strlen(tmp);
    if (b->len + n + 1 > b->cap) {
        b->cap = (b->len + n + 1) * 2;
        b->buf = nihao_realloc(g_cs, b->buf, b->cap);
    }
    memcpy(b->buf + b->len, tmp, n);
    b->len += n;
    b->buf[b->len] = '\0';
}

static const char *cmp_op(IrOp op)
{
    switch (op) {
        case IR_CMP_EQ: return "==";
        case IR_CMP_NE: return "!=";
        case IR_CMP_LT: return "<";
        case IR_CMP_LE: return "<=";
        case IR_CMP_GT: return ">";
        case IR_CMP_GE: return ">=";
        default: return "?";
    }
}

static const char *bin_op(IrOp op)
{
    switch (op) {
        case IR_ADD: return "+";
        case IR_SUB: return "-";
        case IR_MUL: return "*";
        case IR_DIV: return "/";
        case IR_MOD: return "%";
        default: return "?";
    }
}

int irgen_c_emit(IrProg *p, const char *outfile)
{
    CBuf b;
    cb_init(&b);
    cb_put(&b, "/* Generated by ncc IR -> C backend */\n");
    cb_put(&b, "#include <stdio.h>\n#include <stdlib.h>\n#include <stdint.h>\n\n");

    /* 字符串池 */
    for (int i = 0; i < p->str_count; i++) {
        cb_put(&b, "static const char %s[] = \"%s\";\n",
               p->str_syms[i], p->str_data[i]);
    }
    if (p->str_count) cb_put(&b, "\n");

    /* 用户函数前置原型：消除"调用先于定义"导致的隐式声明
     * （Windows tcc 对隐式声明的未知符号生成 __imp_ 外部引用而链接失败） */
    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        cb_put(&b, "int64_t %s(", f->name);
        for (int i = 0; i < f->param_count; i++) {
            cb_put(&b, "%sint64_t arg%d", i ? ", " : "", i);
        }
        cb_put(&b, ");\n");
    }
    if (p->fn_count) cb_put(&b, "\n");

    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        cb_put(&b, "int64_t %s(", f->name);
        for (int i = 0; i < f->param_count; i++) {
            /* 参数名: 子集固定 argN（由 parser 顺序声明） */
            cb_put(&b, "%sint64_t arg%d", i ? ", " : "", i);
        }
        cb_put(&b, ") {\n");
        /* 局部变量声明：遍历全部 vreg——数组基（ALLOCA imm>8）声明为
         * C 数组 t{i}[imm/8]；其余（标量槽/临时）声明单变量。
         * 数组元素 vreg 无 ALLOCA 也声明（未被引用，无害）。 */
        if (f->vreg_count > 0) {
            for (int i = 0; i < f->vreg_count; i++) {
                long long asz = -1;
                for (int ai = 0; ai < f->ins_count; ai++) {
                    if (f->ins[ai].op == IR_ALLOCA && f->ins[ai].dst == i) {
                        asz = (long long)f->ins[ai].imm;
                        break;
                    }
                }
                if (asz > 8) {
                    cb_put(&b, "    int64_t t%d[%lld];\n", i, asz / 8);
                } else {
                    cb_put(&b, "    %s t%d;\n",
                           (f->vreg_type && f->vreg_type[i] == 1) ? "double" : "int64_t", i);
                }
            }
        }
        /* 参数绑定到 vreg 0..nparam-1（parser 先 declare 的参数在 vreg 0..） */
        for (int i = 0; i < f->param_count; i++) {
            cb_put(&b, "    t%d = arg%d;\n", i, i);
        }
        /* 指令 */
        for (int i = 0; i < f->ins_count; i++) {
            IrIns *in = &f->ins[i];
            switch (in->op) {
                case IR_CONST:
                    if (f->vreg_type && in->dst >= 0 && in->dst < f->vreg_count &&
                        f->vreg_type[in->dst] == 1) {
                        /* 浮点常量：imm 是 double 位模式 */
                        union { int64_t i; double d; } u;
                        u.i = in->imm;
                        cb_put(&b, "    t%d = %.17g;\n", in->dst, u.d);
                    } else {
                        cb_put(&b, "    t%d = %lld;\n", in->dst, (long long)in->imm);
                    }
                    break;
                case IR_MOV:
                    cb_put(&b, "    t%d = t%d;\n", in->dst, in->a);
                    break;
                case IR_ADD: case IR_SUB: case IR_MUL:
                case IR_DIV: case IR_MOD:
                    cb_put(&b, "    t%d = t%d %s t%d;\n",
                           in->dst, in->a, bin_op(in->op), in->b);
                    break;
                case IR_FADD: case IR_FSUB: case IR_FMUL: case IR_FDIV:
                    cb_put(&b, "    t%d = t%d %s t%d;\n",
                           in->dst, in->a,
                           in->op == IR_FADD ? "+" :
                           in->op == IR_FSUB ? "-" :
                           in->op == IR_FMUL ? "*" : "/",
                           in->b);
                    break;
                case IR_FCMP:
                    cb_put(&b, "    t%d = (t%d %s t%d);\n",
                           in->dst, in->a,
                           in->imm == 0 ? "==" : in->imm == 1 ? "!=" :
                           in->imm == 2 ? "<"  : in->imm == 3 ? "<=" :
                           in->imm == 4 ? ">"  : ">=",
                           in->b);
                    break;
                case IR_NEG:
                    cb_put(&b, "    t%d = -t%d;\n", in->dst, in->a);
                    break;
                case IR_NOT:
                    cb_put(&b, "    t%d = ~t%d;\n", in->dst, in->a);
                    break;
                case IR_CMP_EQ: case IR_CMP_NE: case IR_CMP_LT:
                case IR_CMP_LE: case IR_CMP_GT: case IR_CMP_GE:
                    cb_put(&b, "    t%d = (t%d %s t%d);\n",
                           in->dst, in->a, cmp_op(in->op), in->b);
                    break;
                case IR_JMP:
                    cb_put(&b, "    goto L%d;\n", in->label);
                    break;
                case IR_JZ:
                    cb_put(&b, "    if (!t%d) goto L%d;\n", in->a, in->label);
                    break;
                case IR_JNZ:
                    cb_put(&b, "    if (t%d) goto L%d;\n", in->a, in->label);
                    break;
                case IR_LABEL:
                    cb_put(&b, "L%d:;\n", in->label);
                    break;
                case IR_LD_ADDR:
                    cb_put(&b, "    t%d = (int64_t)(intptr_t)%s;\n", in->dst, in->sym);
                    break;
                case IR_ALLOCA:
                    /* C 中局部变量已声明；ALLOCA 槽即 t%d */
                    break;
                case IR_ADDR:
                    /* 平铺槽（imm=8）：&t{a+imm} 直接引用槽 vreg；
                     * 基本数组基（imm>8）：&t{a}[imm]（C 数组元素，字节连续） */
                    {
                        long long asz = 8;
                        for (int ai = 0; ai < f->ins_count; ai++) {
                            if (f->ins[ai].op == IR_ALLOCA &&
                                f->ins[ai].dst == in->a) {
                                asz = (long long)f->ins[ai].imm;
                                break;
                            }
                        }
                        if (asz > 8) {
                            cb_put(&b, "    t%d = (int64_t)(intptr_t)&t%d[%lld];\n",
                                   in->dst, in->a, (long long)in->imm);
                        } else {
                            cb_put(&b, "    t%d = (int64_t)(intptr_t)&t%d;\n",
                                   in->dst, in->a + (int)in->imm);
                        }
                    }
                    break;
                case IR_ELEM_ADDR:
                    /* 元素地址 = 基址 + idx*8（C 数组向上，字节连续） */
                    cb_put(&b, "    t%d = t%d + t%d * 8;\n",
                           in->dst, in->a, in->b);
                    break;
                case IR_LOAD:
                    cb_put(&b, "    t%d = *(int64_t*)(intptr_t)t%d;\n",
                           in->dst, in->a);
                    break;
                case IR_STORE:
                    cb_put(&b, "    *(int64_t*)(intptr_t)t%d = t%d;\n",
                           in->a, in->b);
                    break;
                case IR_RET:
                    if (in->a >= 0)
                        cb_put(&b, "    return t%d;\n", in->a);
                    else
                        cb_put(&b, "    return 0;\n");
                    break;
                case IR_PARAM:
                    /* 收集：由紧随其后的 CALL 处理 */
                    break;
                case IR_CALL: {
                    /* 取本 CALL 前最近的 nargs 个 PARAM */
                    int nargs = (int)in->imm;
                    int temp[64];
                    int tc = 0;
                    for (int k = 0; k < i && tc < 64; k++) {
                        if (f->ins[k].op == IR_PARAM) temp[tc++] = f->ins[k].a;
                    }
                    int start = tc > nargs ? tc - nargs : 0;
                    cb_put(&b, "    t%d = %s(", in->dst, in->sym);
                    for (int k = start; k < tc; k++) {
                        cb_put(&b, "%st%d", k > start ? ", " : "", temp[k]);
                    }
                    cb_put(&b, ");\n");
                    break;
                }
                case IR_CALLI: {
                    /* 间接调用：dst = call *(a)，旧式无原型函数指针 */
                    int nargs = (int)in->imm;
                    int temp[64];
                    int tc = 0;
                    for (int k = 0; k < i && tc < 64; k++) {
                        if (f->ins[k].op == IR_PARAM) temp[tc++] = f->ins[k].a;
                    }
                    int start = tc > nargs ? tc - nargs : 0;
                    cb_put(&b, "    t%d = ((int64_t (*)())t%d)(", in->dst, in->a);
                    for (int k = start; k < tc; k++) {
                        cb_put(&b, "%st%d", k > start ? ", " : "", temp[k]);
                    }
                    cb_put(&b, ");\n");
                    break;
                }
                default:
                    break;
            }
        }
        cb_put(&b, "    return 0;\n}\n\n");
    }

    FILE *fp = fopen(outfile, "wb");
    if (!fp) {
        fprintf(stderr, "ir-c: cannot write '%s'\n", outfile);
        return -1;
    }
    fputs(b.buf, fp);
    fclose(fp);
    if (g_cs && g_cs->verbose) {
        printf("IR->C written to %s (%d bytes)\n", outfile, b.len);
    }
    return 0;
}
