/* ============================================================
 * ir_to_c.c - IR -> C 后端（方案 B）
 * 每条 IR 指令翻译为一行 C，字符串池输出为静态数组
 * ============================================================ */
#include "ir.h"

typedef struct {
    char *buf;
    int len, cap;
} CBuf;

static void cb_init(CBuf *b)
{
    b->cap = 4096;
    b->buf = nihao_malloc(g_cs, b->cap);
    b->buf[0] = '\0';
    b->len = 0;
}

static void cb_put(CBuf *b, const char *fmt, ...)
{
    char tmp[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(tmp, sizeof(tmp), fmt, ap);
    va_end(ap);
    int n = (int)strlen(tmp);
    if (b->len + n + 1 > b->cap) {
        b->cap = (b->len + n + 1) * 2;
        b->buf = nihao_realloc(g_cs, b->buf, b->cap);
    }
    memcpy(b->buf + b->len, tmp, n);
    b->len += n;
    b->buf[b->len] = '\0';
}

static const char *cmp_op(IrOp op)
{
    switch (op) {
        case IR_CMP_EQ: return "==";
        case IR_CMP_NE: return "!=";
        case IR_CMP_LT: return "<";
        case IR_CMP_LE: return "<=";
        case IR_CMP_GT: return ">";
        case IR_CMP_GE: return ">=";
        default: return "?";
    }
}

static const char *bin_op(IrOp op)
{
    switch (op) {
        case IR_ADD: return "+";
        case IR_SUB: return "-";
        case IR_MUL: return "*";
        case IR_DIV: return "/";
        case IR_MOD: return "%";
        default: return "?";
    }
}

int irgen_c_emit(IrProg *p, const char *outfile)
{
    CBuf b;
    cb_init(&b);
    cb_put(&b, "/* Generated by ncc IR -> C backend */\n");
    cb_put(&b, "#include <stdio.h>\n#include <stdlib.h>\n#include <stdint.h>\n\n");

    /* 字符串池 */
    for (int i = 0; i < p->str_count; i++) {
        cb_put(&b, "static const char %s[] = \"%s\";\n",
               p->str_syms[i], p->str_data[i]);
    }
    if (p->str_count) cb_put(&b, "\n");

    /* 用户函数前置原型：消除"调用先于定义"导致的隐式声明
     * （Windows tcc 对隐式声明的未知符号生成 __imp_ 外部引用而链接失败） */
    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        cb_put(&b, "int64_t %s(", f->name);
        for (int i = 0; i < f->param_count; i++) {
            cb_put(&b, "%sint64_t arg%d", i ? ", " : "", i);
        }
        cb_put(&b, ");\n");
    }
    if (p->fn_count) cb_put(&b, "\n");

    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        cb_put(&b, "int64_t %s(", f->name);
        for (int i = 0; i < f->param_count; i++) {
            /* 参数名: 子集固定 argN（由 parser 顺序声明） */
            cb_put(&b, "%sint64_t arg%d", i ? ", " : "", i);
        }
        cb_put(&b, ") {\n");
        /* 局部变量声明：统一 64 位（IR_ADDR/IR_LOAD/IR_STORE 以 8 字节槽工作） */
        if (f->vreg_count > 0) {
            cb_put(&b, "    int64_t ");
            for (int i = 0; i < f->vreg_count; i++) {
                cb_put(&b, "t%d%s", i, i + 1 < f->vreg_count ? ", " : "");
            }
            cb_put(&b, ";\n");
        }
        /* 参数绑定到 vreg 0..nparam-1（parser 先 declare 的参数在 vreg 0..） */
        for (int i = 0; i < f->param_count; i++) {
            cb_put(&b, "    t%d = arg%d;\n", i, i);
        }
        /* 指令 */
        for (int i = 0; i < f->ins_count; i++) {
            IrIns *in = &f->ins[i];
            switch (in->op) {
                case IR_CONST:
                    cb_put(&b, "    t%d = %lld;\n", in->dst, (long long)in->imm);
                    break;
                case IR_MOV:
                    cb_put(&b, "    t%d = t%d;\n", in->dst, in->a);
                    break;
                case IR_ADD: case IR_SUB: case IR_MUL:
                case IR_DIV: case IR_MOD:
                    cb_put(&b, "    t%d = t%d %s t%d;\n",
                           in->dst, in->a, bin_op(in->op), in->b);
                    break;
                case IR_NEG:
                    cb_put(&b, "    t%d = -t%d;\n", in->dst, in->a);
                    break;
                case IR_NOT:
                    cb_put(&b, "    t%d = ~t%d;\n", in->dst, in->a);
                    break;
                case IR_CMP_EQ: case IR_CMP_NE: case IR_CMP_LT:
                case IR_CMP_LE: case IR_CMP_GT: case IR_CMP_GE:
                    cb_put(&b, "    t%d = (t%d %s t%d);\n",
                           in->dst, in->a, cmp_op(in->op), in->b);
                    break;
                case IR_JMP:
                    cb_put(&b, "    goto L%d;\n", in->label);
                    break;
                case IR_JZ:
                    cb_put(&b, "    if (!t%d) goto L%d;\n", in->a, in->label);
                    break;
                case IR_JNZ:
                    cb_put(&b, "    if (t%d) goto L%d;\n", in->a, in->label);
                    break;
                case IR_LABEL:
                    cb_put(&b, "L%d:;\n", in->label);
                    break;
                case IR_LD_ADDR:
                    cb_put(&b, "    t%d = (int64_t)(intptr_t)%s;\n", in->dst, in->sym);
                    break;
                case IR_ALLOCA:
                    /* C 中局部变量已声明；ALLOCA 槽即 t%d */
                    break;
                case IR_ADDR:
                    /* ALLOCA 为每个槽分配独立 vreg（t{a}, t{a+1}, ...），
                     * imm=k 直接引用槽 vreg 的地址，不依赖 C 栈连续布局 */
                    cb_put(&b, "    t%d = (int64_t)(intptr_t)&t%d;\n",
                           in->dst, in->a + (int)in->imm);
                    break;
                case IR_LOAD:
                    cb_put(&b, "    t%d = *(int64_t*)(intptr_t)t%d;\n",
                           in->dst, in->a);
                    break;
                case IR_STORE:
                    cb_put(&b, "    *(int64_t*)(intptr_t)t%d = t%d;\n",
                           in->a, in->b);
                    break;
                case IR_RET:
                    if (in->a >= 0)
                        cb_put(&b, "    return t%d;\n", in->a);
                    else
                        cb_put(&b, "    return 0;\n");
                    break;
                case IR_PARAM:
                    /* 收集：由紧随其后的 CALL 处理 */
                    break;
                case IR_CALL: {
                    /* 取本 CALL 前最近的 nargs 个 PARAM */
                    int nargs = (int)in->imm;
                    int temp[64];
                    int tc = 0;
                    for (int k = 0; k < i && tc < 64; k++) {
                        if (f->ins[k].op == IR_PARAM) temp[tc++] = f->ins[k].a;
                    }
                    int start = tc > nargs ? tc - nargs : 0;
                    cb_put(&b, "    t%d = %s(", in->dst, in->sym);
                    for (int k = start; k < tc; k++) {
                        cb_put(&b, "%st%d", k > start ? ", " : "", temp[k]);
                    }
                    cb_put(&b, ");\n");
                    break;
                }
                default:
                    break;
            }
        }
        cb_put(&b, "    return 0;\n}\n\n");
    }

    FILE *fp = fopen(outfile, "wb");
    if (!fp) {
        fprintf(stderr, "ir-c: cannot write '%s'\n", outfile);
        return -1;
    }
    fputs(b.buf, fp);
    fclose(fp);
    if (g_cs && g_cs->verbose) {
        printf("IR->C written to %s (%d bytes)\n", outfile, b.len);
    }
    return 0;
}
