/* ============================================================
 * ir_to_native.c - IR -> x86-64 AT&T 汇编（方案 B）
 *
 * 极简后端：虚拟寄存器全部映射为 rbp 栈槽（无寄存器分配），
 * 由 tcc 内置汇编器完成汇编与链接。调用遵循 Windows x64 ABI
 * （前 4 参数 rcx/rdx/r8/r9 + 32 字节 shadow space）。
 * ============================================================ */
#include "ir.h"

typedef struct {
    char *buf;
    int len, cap;
} NBuf;

static void nb_init(NBuf *b)
{
    b->cap = 4096;
    b->buf = nihao_malloc(g_cs, b->cap);
    b->buf[0] = '\0';
    b->len = 0;
}

static void nb_put(NBuf *b, const char *fmt, ...)
{
    char tmp[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(tmp, sizeof(tmp), fmt, ap);
    va_end(ap);
    int n = (int)strlen(tmp);
    if (b->len + n + 1 > b->cap) {
        b->cap = (b->len + n + 1) * 2;
        b->buf = nihao_realloc(g_cs, b->buf, b->cap);
    }
    memcpy(b->buf + b->len, tmp, n);
    b->len += n;
    b->buf[b->len] = '\0';
}

/* vreg -> 栈槽 */
static void slot(NBuf *b, int vreg)
{
    nb_put(b, "-%d(%%rbp)", 8 * (vreg + 1));
}

static const char *setcc_ins(IrOp op)
{
    switch (op) {
        case IR_CMP_EQ: return "sete";
        case IR_CMP_NE: return "setne";
        case IR_CMP_LT: return "setl";
        case IR_CMP_LE: return "setle";
        case IR_CMP_GT: return "setg";
        case IR_CMP_GE: return "setge";
        default: return "sete";
    }
}

static const char *jcc_ins(IrOp op)
{
    switch (op) {
        case IR_JZ:  return "je";
        case IR_JNZ: return "jne";
        default: return "jmp";
    }
}

int irgen_native_emit(IrProg *p, const char *outfile)
{
    NBuf b;
    nb_init(&b);
    nb_put(&b, "# Generated by ncc IR -> x86-64 backend\n");
    nb_put(&b, ".text\n");

    /* 字符串池 */
    if (p->str_count > 0) {
        nb_put(&b, ".section .rodata\n");
        for (int i = 0; i < p->str_count; i++) {
            nb_put(&b, "%s:\n", p->str_syms[i]);
            nb_put(&b, "  .string \"%s\"\n", p->str_data[i]);
        }
        nb_put(&b, ".text\n");
    }

    for (int fi = 0; fi < p->fn_count; fi++) {
        IrFn *f = &p->fns[fi];
        /* 帧大小：保证 rsp 在 call 点 16 字节对齐。
         * 入口 rsp≡0 -> push rbp 后 ≡8 -> sub frame 后需 ≡8 (mod 16)。 */
        int frame = 8 * (f->vreg_count + 1);
        if (frame % 16 == 0) frame += 8;
        if (f->is_main) {
            nb_put(&b, ".globl main\n");
        }
        nb_put(&b, "%s:\n", f->name);
        nb_put(&b, "  pushq %%rbp\n");
        nb_put(&b, "  movq %%rsp, %%rbp\n");
        nb_put(&b, "  subq $%d, %%rsp\n", frame);
        /* 参数: rcx/rdx/r8/r9 -> vreg 0..nparam-1 */
        const char *parg[4] = { "%rcx", "%rdx", "%r8", "%r9" };
        for (int i = 0; i < f->param_count && i < 4; i++) {
            nb_put(&b, "  movq %s, ", parg[i]);
            slot(&b, i);
            nb_put(&b, "\n");
        }

        /* 指令 */
        for (int i = 0; i < f->ins_count; i++) {
            IrIns *in = &f->ins[i];
            switch (in->op) {
                case IR_CONST:
                    nb_put(&b, "  movq $%lld, ", (long long)in->imm);
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_MOV:
                    nb_put(&b, "  movq ");
                    slot(&b, in->a);
                    nb_put(&b, ", %%rax\n  movq %%rax, ");
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_ADD: case IR_SUB:
                    nb_put(&b, "  movq ");
                    slot(&b, in->a);
                    nb_put(&b, ", %%rax\n  %sq ", in->op == IR_ADD ? "add" : "sub");
                    slot(&b, in->b);
                    nb_put(&b, ", %%rax\n  movq %%rax, ");
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_MUL:
                    nb_put(&b, "  movq ");
                    slot(&b, in->a);
                    nb_put(&b, ", %%rax\n  imulq ");
                    slot(&b, in->b);
                    nb_put(&b, ", %%rax\n  movq %%rax, ");
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_DIV: case IR_MOD:
                    nb_put(&b, "  movq ");
                    slot(&b, in->a);
                    nb_put(&b, ", %%rax\n  cqto\n  idivq ");
                    slot(&b, in->b);
                    nb_put(&b, "\n");
                    if (in->op == IR_DIV) {
                        nb_put(&b, "  movq %%rax, ");
                    } else {
                        nb_put(&b, "  movq %%rdx, ");
                    }
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_NEG:
                    nb_put(&b, "  movq ");
                    slot(&b, in->a);
                    nb_put(&b, ", %%rax\n  negq %%rax\n  movq %%rax, ");
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_CMP_EQ: case IR_CMP_NE: case IR_CMP_LT:
                case IR_CMP_LE: case IR_CMP_GT: case IR_CMP_GE:
                    nb_put(&b, "  movq ");
                    slot(&b, in->a);
                    nb_put(&b, ", %%rax\n  cmpq ");
                    slot(&b, in->b);
                    nb_put(&b, ", %%rax\n  %s %%al\n  movzbq %%al, %%rax\n  movq %%rax, ",
                           setcc_ins(in->op));
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_JMP:
                    nb_put(&b, "  jmp .L%d\n", in->label);
                    break;
                case IR_JZ: case IR_JNZ:
                    nb_put(&b, "  cmpq $0, ");
                    slot(&b, in->a);
                    nb_put(&b, "\n  %s .L%d\n", jcc_ins(in->op), in->label);
                    break;
                case IR_LABEL:
                    nb_put(&b, ".L%d:\n", in->label);
                    break;
                case IR_LD_ADDR:
                    nb_put(&b, "  leaq %s(%%rip), %%rax\n  movq %%rax, ",
                           in->sym);
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                case IR_ALLOCA:
                    break;   /* 槽即栈位置 */
                case IR_PARAM:
                    break;   /* 由 CALL 处理 */
                case IR_CALL: {
                    /* 取本 CALL 前最近的 nargs 个 PARAM */
                    int nargs = (int)in->imm;
                    int temp[64];
                    int tc = 0;
                    for (int k = 0; k < i && tc < 64; k++) {
                        if (f->ins[k].op == IR_PARAM) temp[tc++] = f->ins[k].a;
                    }
                    int start = tc > nargs ? tc - nargs : 0;
                    int args[64];
                    int got = tc - start;
                    for (int k = 0; k < got; k++) args[k] = temp[start + k];
                    const char *regs[4] = { "%rcx", "%rdx", "%r8", "%r9" };
                    for (int k = 0; k < got && k < 4; k++) {
                        nb_put(&b, "  movq ");
                        slot(&b, args[k]);
                        nb_put(&b, ", %s\n", regs[k]);
                    }
                    if (got > 4) {
                        /* 多余参数压栈（从右到左） */
                        for (int k = got - 1; k >= 4; k--) {
                            nb_put(&b, "  pushq ");
                            slot(&b, args[k]);
                            nb_put(&b, "\n");
                        }
                    }
                    nb_put(&b, "  subq $32, %%rsp\n");   /* shadow space */
#ifdef _WIN32
                    /* tcc 汇编器对 call sym 会直接跳 IAT 槽(数据区)；
                     * 外部导入函数须经 __imp_ 间接调用 */
                    nb_put(&b, "  call *__imp_%s(%%rip)\n", in->sym);
#else
                    nb_put(&b, "  call %s\n", in->sym);
#endif
                    nb_put(&b, "  addq $%d, %%rsp\n", 32 + (got > 4 ? 8 * (got - 4) : 0));
                    nb_put(&b, "  movq %%rax, ");
                    slot(&b, in->dst);
                    nb_put(&b, "\n");
                    break;
                }
                case IR_RET:
                    if (in->a >= 0) {
                        nb_put(&b, "  movq ");
                        slot(&b, in->a);
                        nb_put(&b, ", %%rax\n");
                    } else {
                        nb_put(&b, "  xorl %%eax, %%eax\n");
                    }
                    nb_put(&b, "  leave\n  ret\n");
                    break;
                default:
                    break;
            }
        }
        nb_put(&b, "\n");
    }

    FILE *fp = fopen(outfile, "wb");
    if (!fp) {
        fprintf(stderr, "ir-native: cannot write '%s'\n", outfile);
        return -1;
    }
    fputs(b.buf, fp);
    fclose(fp);
    if (g_cs && g_cs->verbose) {
        printf("IR->asm written to %s (%d bytes)\n", outfile, b.len);
    }
    return 0;
}
